create extension if not exists citext;

create table if not exists public.fiyu_user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username citext not null unique check (username::text ~ '^[a-z0-9_]{3,30}$'),
  auth_email citext not null unique,
  display_name text check (display_name is null or char_length(display_name) <= 50),
  bio text check (bio is null or char_length(bio) <= 160),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fiyu_restaurant_lists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  city_id text not null,
  name text not null check (btrim(name) <> '' and char_length(name) <= 80),
  list_kind text not null check (list_kind in ('default', 'custom')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(id, user_id)
);
create unique index if not exists fiyu_lists_one_default_per_city
  on public.fiyu_restaurant_lists(user_id, city_id) where list_kind = 'default';
create index if not exists fiyu_lists_user_city
  on public.fiyu_restaurant_lists(user_id, city_id, created_at);

create table if not exists public.fiyu_restaurant_list_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  list_id bigint not null,
  place_id text not null,
  created_at timestamptz not null default now(),
  unique(list_id, place_id),
  foreign key(list_id, user_id)
    references public.fiyu_restaurant_lists(id, user_id) on delete cascade
);
create index if not exists fiyu_list_items_user on public.fiyu_restaurant_list_items(user_id, list_id);

create table if not exists public.fiyu_restaurant_visits (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  place_id text not null,
  visited_at timestamptz not null,
  reaction text not null check (reaction in ('love_it', 'like_it', 'not_for_me')),
  private_note text check (private_note is null or char_length(private_note) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists fiyu_visits_user_date on public.fiyu_restaurant_visits(user_id, visited_at desc);
create index if not exists fiyu_visits_user_place on public.fiyu_restaurant_visits(user_id, place_id);

create table if not exists public.fiyu_restaurant_seen (
  user_id uuid not null references auth.users(id) on delete cascade,
  place_id text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  seen_count integer not null default 1 check (seen_count > 0),
  primary key(user_id, place_id)
);
create index if not exists fiyu_seen_user_recent on public.fiyu_restaurant_seen(user_id, last_seen_at desc);

create or replace function public.record_fiyu_seen(p_user_id uuid, p_place_ids text[])
returns void language sql security definer set search_path = public as $$
  insert into public.fiyu_restaurant_seen(user_id, place_id)
  select p_user_id, place_id from unnest(p_place_ids) as place_id
  on conflict (user_id, place_id) do update
    set last_seen_at = greatest(fiyu_restaurant_seen.last_seen_at, now());
$$;
revoke all on function public.record_fiyu_seen(uuid, text[]) from public, anon, authenticated;
grant execute on function public.record_fiyu_seen(uuid, text[]) to service_role;

alter table public.fiyu_user_profiles enable row level security;
alter table public.fiyu_restaurant_lists enable row level security;
alter table public.fiyu_restaurant_list_items enable row level security;
alter table public.fiyu_restaurant_visits enable row level security;
alter table public.fiyu_restaurant_seen enable row level security;

create policy "profiles own rows" on public.fiyu_user_profiles for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "lists own rows" on public.fiyu_restaurant_lists for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "list items own rows" on public.fiyu_restaurant_list_items for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "visits own rows" on public.fiyu_restaurant_visits for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "seen own rows" on public.fiyu_restaurant_seen for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
